#!/usr/bin/env python
import time
delay = 1
apples = 0
gold = 0
name = ''
yes = ['Y','y','yes','Yes']
no = ['N','n','no','No']

def start():
    global name
    print("Hello and welcome!")
    name=raw_input("What's your name: ")
    print("Welcome, " + name + "!")
    print("The objective of this game is to collect apples.")
    print("After collecting the apples you sell them.")
    choice = raw_input("Do you want to play Y/N?")
    if choice in yes:
        print "Let's get started!"
        begin()
    elif choice in no:
        print "Okay, bye..."
        exit()
    else:
        exit()

def printInventory(apples):
    suff = '' if apples == 1 else 's'
    print "You currently have,",apples,'apple'+suff

def begin():
    global apples
    global gold
    global name
    pick = raw_input("Do you want to pick an apple? Y/N: ")
    if pick in yes:
        time.sleep(delay)
        print("Pick an apple")
        apples += 1
        printInventory(apples)
        begin()
    elif pick in no:
        sell = raw_input("Do you want to sell your apples? Y/N: ")
        if sell in yes:
            printInventory(apples)
            if int(apples) < 1:
                print("Sorry, " +name+ " . You have no apples to sell.")
            elif int(apples)==1:
                print("You've sold your apple.")
                gold = apples*10
            else:
                print("You've sold your apples.")
                gold = apples*10
            apples = 0
        elif sell in no:
            print("Okay, have fun with your apple.")
        else:
            print("Should have followed my instructions. Have fun at the beginning!")
        begin()

start()
